### ISSUE TITLE
Channel ID

### ISSUE THREAD

**Issue by premtemp1** [moshen/node-googlemaps#103]
Does this library support channel ID?

**Comment by moshen** [comment]
I have never used this feature.  Googling doesn't really help either.  Care to explain?

**Comment by ggoodale** [comment]
From [Google's pre-launch checklist](https://developers.google.com/maps/premium/prelaunch-checklist#channel): 

> A channel parameter is an optional parameter that allows you to track usage under your client ID by assigning a distinct channel to each of your applications. Channel parameters do not need to be registered to your client ID. By adding the channel parameter to your API request, the usage results per channel will begin to appear in your support portal usage reports 1-2 days after implementation.

I think it's simply a matter of adding `channel` to the allowed list of params to each API call (as well as plumbing them through to the url.

**Comment by fabriziomoscon** [comment]
https://github.com/moshen/node-googlemaps/pull/116
