### ISSUE TITLE
Image binary encoding?

### ISSUE THREAD

**Issue by mikepc** [moshen/node-googlemaps#108]
I'm using staticMap to generate a binary map image.

When I use the following code:

    fs.writeFile('testblob.png', mapImage, (err) => {
      if (err) throw err;
      console.log('It\'s saved!');
    });

The testblob.png is unreadable.  What do I need to do with this binary buffer in order to read it after writing it?

**Comment by moshen** [comment]
What is `mapImage`?  Could you post a longer example?

**Comment by mikepc** [comment]
I fixed the problem, it was a content encoding issue with s3, I needed to set it to binary.  

Sent from Outlook Mobile




On Sun, Mar 20, 2016 at 4:45 PM -0700, "Colin Kennedy" <notifications@github.com> wrote:












What is mapImage?  Could you post a longer example?
