### ISSUE TITLE
Does it support the geometry library?

### ISSUE THREAD

**Issue by colingoldberg** [moshen/node-googlemaps#109]
Hi,

I would like to use the geometry library within my nodejs application. Is this supported? If not, is it on the roadmap?

Thanks

Colin Goldberg

**Comment by fabriziomoscon** [comment]
as far as I can see:
https://developers.google.com/maps/documentation/javascript/geometry#Geometry
the Geometry library is an extension of the Javascript Google maps library. That is meant to be used on the browser. This repository is intended for the server side Google maps calls. I think the Google Javascript library is much more sophisticated than this repository which is simply a wrapper for authenticated HTTP calls without access to the Map object and other libraries that Google provides in the Javascript SDK.

Please feel free to reopen this in case you see any way to use the Geometry library on the server
