### ISSUE TITLE
Is there a way to calculate center for multiple points.

### ISSUE THREAD

**Issue by jitendra-kr** [moshen/node-googlemaps#143]
Hi, 

I am working on car tracking application in nodeJs. 

1. I have 100 to 100000 coordinates for a trip. After drawing path on map. Now i need to set a valid center of map. I am stuck here.
2. How can i pass lat, long instead of address 

  markers: [
    {
      location: 'C-20/1, Sector-62, Noida, Uttar Pradesh 201301',
      label   : 'S',
      color   : 'green',
      shadow  : true,

    }

is there a way use only lat, long instead of (C-20/1, Sector-62, Noida, Uttar Pradesh 201301).

**Comment by Liamdelee** [comment]
Lat Long can be passed like '51.06199,4.362622' note the **'**.
for the center if you use static map just remove the center and zoom tags and google will auto search for the best center and zoom for your call. documented [here](https://developers.google.com/maps/documentation/static-maps/intro#ImplicitPositioning)

```
example:
var params = {
  size: '640x640',
  maptype: 'roadmap',
  markers: [
    {
      location: LatLong1,
      label   : '1',
      color   : 'green',
      shadow  : true
    },
    {
      location: LatLong2,
      label   : '2',
      color   : 'blue',
      shadow  : true
    },
    {
      location: LatLong3,
      label   : '3',
      color   : 'red',
      shadow  : true
    }
  ],
  style: [
    {
      feature: 'road',
      element: 'all',
      rules: {
        hue: '0x00ff00'
      }
    }
  ]
};
```

**Comment by jitendra-kr** [comment]
Thanks Liamdelee
