### ISSUE TITLE
Proxy doc or example?

### ISSUE THREAD

**Issue by namezero** [moshen/node-googlemaps#66]
hi,
does the proxy let to avoid  the max usage limit? 
is there any example please?
thanks

**Comment by moshen** [comment]
> does the proxy let to avoid the max usage limit?

If you're referring to the limits on the [JavaScript API](https://developers.google.com/maps/documentation/javascript/), then no.  The Maps APIs subject to [usage limits are defined in the Google documentation](https://developers.google.com/maps/faq#usagelimits).  The Maps APIs with limits require an authentication token, which Google (undoubtedly) uses to track usage.

If you're talking about circumventing _abuse_ level usage on anonymously connected apis, I would like to discourage you from such action.  Unless your site/project is pulling serious traffic, you probably wont hit any of these limits.

> is there any example please?

Set the proxy url like so:

    var gm = require('googlemaps');
    gm.config('proxy', 'url');

The provided url is passed directly into [request options](https://github.com/request/request#proxies) and is assumed to be an HTTP proxy.

**Comment by namezero** [comment]
my web app is pulling serious traffic, i found a good solution : 

the first node script is doing directions requests, when it reach usage limit, it send on a topic,
and a second node (on other server) listening to that topic and doing directions script again, imagine that this script can also push messages in new topic and other node in other server doing the same...
