### ISSUE TITLE
Order of response values is different than the client side google maps api

### ISSUE THREAD

**Issue by stephengardner** [moshen/node-googlemaps#67]
I noticed this while doing geocoding.  It looks like you've implemented these functions to have the first parameter be the potential error value and the second parameter be the results, but the google maps api shows this format:
` geocoder.geocode( { 'address': address}, function(results, status) {
...
});
`
While noting this example, it also doesn't look like you allow an object for the address, only an address string itself.
I was thinking it would be nice to have these formats identical, or at the very least, more substantially documented.  I think this is a great module so far.

**Comment by moshen** [comment]
> I noticed this while doing geocoding. It looks like you've implemented these functions to have the first parameter be the potential error value and the second parameter be the results

[Having the first parameter of the callback is a nodejs convention](http://thenodeway.io/posts/understanding-error-first-callbacks/) and this lib will be sticking to that.

> While noting this example, it also doesn't look like you allow an object for the address, only an address string itself.

The apis are different.  [The Google docs state the address is passed in as a string](https://developers.google.com/maps/documentation/geocoding/?csw=1#geocoding).  [They provide further insight into formatting in the faq](https://developers.google.com/maps/faq#geocoder_queryformat).  It's probably a better idea to do localized address handling in another module and pass the resulting strings to `googlemaps`.
