### ISSUE TITLE
Lat and lng of geocoder response

### ISSUE THREAD

**Issue by stephengardner** [moshen/node-googlemaps#68]
for a proper geocoded response, there is the geometry property, which has a location and that location has a lat and lng, but these are not parameters, they are getters, (they are functions).
i.e.: 
the way google does it: `googleResultObject.geometry.location.lat()` 
the way this module does it: `googleResultObject.geometry.location.lat`.

This can be confusing.  I'd simply add this to the readme.

**Comment by moshen** [comment]
[You are conflating the front-end js api](https://developers.google.com/maps/documentation/javascript/reference#LatLng) with this one, which calls the google services.  This module is simply passing back the decoded json output [as defined by the Google service](https://developers.google.com/maps/documentation/geocoding/?csw=1#JSON).
