### ISSUE TITLE
return result

### ISSUE THREAD

**Issue by mezoo** [moshen/node-googlemaps#76]
Hi,

I don't understand how make result function, I m trying to do this :+1: 

    var result;
    gm.distance(from,to,function(err,data){
      result = data;
    });
    console.log(result);

Output : undefined

It is possible to return result directly

**Comment by moshen** [comment]
Try:

    var result;
    gm.distance(from,to,function(err,data){
      result = data;
      console.log(result);
    });

No, it's not possible to return the result directly (with the current api).  It makes an asynchronous call to the google maps api.
