### ISSUE TITLE
Check point inside polygon otr not?

### ISSUE THREAD

**Issue by surendrakumar1992** [moshen/node-googlemaps#78]
How can draw a polygon on google map and check if point inside a polygon or not?

**Comment by moshen** [comment]
I'm guessing that you're referring to the [Google maps (frontend) javascript api](https://developers.google.com/maps/documentation/javascript/), more specifically [the geometry library](https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation).

If you're trying to do this on a nodejs server, then you will need to recreate/find some of the functionality of the geometry library available on the front-end.
