### ISSUE TITLE
Request Denied

### ISSUE THREAD

**Issue by niguloto** [moshen/node-googlemaps#81]
Hello Colin,

Thank you so much for making this library for gMaps/node!! 
[EDIT: solved the original problem, new question though!]

Second question: I'm having some issues with Google Deniing some request:
{ error_message: 'This API project is not authorized to use this API. Please ensure that this API is activated in the APIs Console: Learn more: https://code.google.com/apis/console',
  results: [],
  status: 'REQUEST_DENIED' }

No big deal, I can selectively delete each key in the config var but will there be a reference in the log in the future that points specifically towards the one is been denied?

Thank you so much for your work,
Nicolò

**Comment by fabriziomoscon** [comment]
Hi @niguloto,

I suppose you are using `v1.0.0`
If you are using a standard api key from https://code.google.com/apis/console refer to this example
https://github.com/moshen/node-googlemaps/blob/master/test/simpleConfig.json
and implementation from the integration tests:
https://github.com/moshen/node-googlemaps/tree/master/test/integration

It was decided to pass back the error as Google display it in order not to add extra code for error parsing and so not to confuse the developer who might ask help directly to Google or other Q&A popular websites.

Google error is not accurate to prevent information leaking to malicious users.

In case you are using the google maps for work (or Enterprise) you will need to *omit* the `key` and use `google_client_id` and `google_private_key`

(REDME.md just been updated with an example)

Thanks

**Comment by niguloto** [comment]
Hey Fabrizio,

Thank you so much for your answer. Yes, I'm using v1.0.0.
All clear, thanks for all the helpful links!

Best,
Nicolò
