### ISSUE TITLE
multi points itinerary

### ISSUE THREAD

**Issue by smolleyes** [moshen/node-googlemaps#83]
hi

is it possible to build something like this.... with google api?

1 / i enter a list of 25 or more addresses
2 / api calculate the best / fastest itinerary from ALL those points
3 / have a list as a result or export this as xls ? 

thanks

**Comment by fabriziomoscon** [comment]
Hi @smolleyes,

you can have a look at this method: https://developers.google.com/maps/documentation/distancematrix/

There are limitation from Google on the way you will display the results.

**Comment by smolleyes** [comment]
Hello

Thanks for the reply :)

Free api is limited To 100 elements by query does it mean 100 adresses on my case ? (Nice if it s right)

Think i ll try To put all my points on a map then create an entry and end point possible then send geocoded values of each points To this api ...

Seems right for you ?

Thanks a lot

**Comment by fabriziomoscon** [comment]
I believe you have the following limitations:

```
Users of the free API:
100 elements per query.
100 elements per 10 seconds.
2500 elements per 24 hour period.
```

The 100 elements - I guess - are a combination or `origins` and `destinations` - but I am not sure. You would need to test by yourself what is the free limit. Google will give you an error when you exceed the limits.





I am sorry but I am not really understanding what you want to achieve.
You would need to re-formulate your problem in a way we can
