### ISSUE TITLE
Static map - can only generate a single style

### ISSUE THREAD

**Issue by rayshan** [moshen/node-googlemaps#86]
Hi,

`1.0.1`

Params with a single style object:

```js
var params = {
    center: '44.9545,-93.3365',
    zoom: 10,
    size: '640x640',
    scale: 2,
    maptype: 'roadmap',
    style: [
        {
            feature: 'all',
            rules: {
                invert_lightness: true,
                hue: '0x57574e'
            }
        }
    ]
}
```

Correctly generates:

https://maps.googleapis.com/maps/api/staticmap?center=44.9545%2C-93.3365&zoom=10&size=640x640&scale=2&maptype=roadmap&style=feature%3Aall%7Cinvert_lightness%3Atrue%7Chue%3A0x57574e&key=xyz

![staticmap](https://cloud.githubusercontent.com/assets/3760840/8945812/b8500172-353f-11e5-9366-cc8d2f6133aa.png)

But when there are multiple style objects:

```js
var params = {
    center: '44.9545,-93.3365',
    zoom: 10,
    size: '640x640',
    scale: 2,
    maptype: 'roadmap',
    style: [
        {
            feature: 'all',
            rules: {
                invert_lightness: true,
                hue: '0x57574e'
            }
        },
        {
            feature: 'road.highway',
            rules: {
                visibility: "simplified"
            }
        }
    ]
}
```

Generated URI is missing `&style=`: https://maps.googleapis.com/maps/api/staticmap?center=44.9545%2C-93.3365&zoom=10&size=640x640&scale=2&maptype=roadmap&style=feature%3Aall%7Cinvert_lightness%3Atrue%7Chue%3A0x57574e%7Cfeature%3Aroad.highway%7Cvisibility%3Asimplified&key=xyz

![staticmap-1](https://cloud.githubusercontent.com/assets/3760840/8945821/ca15b550-353f-11e5-869d-16ce480e64c2.png)

Expected: https://maps.googleapis.com/maps/api/staticmap?center=44.9545%2C-93.3365&zoom=10&size=640x640&scale=2&maptype=roadmap&style=feature%3Aall%7Cinvert_lightness%3Atrue%7Chue%3A0x57574e%7C&style=feature%3Aroad.highway%7Cvisibility%3Asimplified&key=xyz

![staticmap-2](https://cloud.githubusercontent.com/assets/3760840/8945904/9a15ee00-3540-11e5-8a00-69e1f116b0c4.png)

The test is also missing `&style=`: https://github.com/moshen/node-googlemaps/blob/master/test/unit/utils/parseStylesTest.js#L48

**Comment by felix** [comment]
See my pull request #87 for a possible solution
