### ISSUE TITLE
Possible alternatives to callbacks? Promise / Observables

### ISSUE THREAD

**Issue by vikeen** [moshen/node-googlemaps#96]
I saw this reference in the v1.0 refactor by @moshen. Any thoughts on this?

**Comment by vikeen** [comment]
Current implementation for me with callbacks

   
```js 
return new Bluebird(function (resolve, reject) {
        googleMapsAPI.placeSearch(options, function (error, response) {
            winston.debug("placeSearch result:", response);

            if (error) {
                return reject("Unable to query google maps api placeSearch", error);
            }

            return resolve(response);
        });
    });
```

With straight promises

```js 
return googleMapsAPI.placeSearch(options)
    .then(function (response) {
        winston.debug("placeSearch result:", response);
    })
    .catch(function (e) {
        winston.error("Unable to query google maps api placeSearch");
    });
```

**Comment by moshen** [comment]
Since all the calls now follow a similar pattern (CPS, callback last), you can [use Bluebird to `promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html) on the object.  So your example becomes:

```javascript
var Promise = require('bluebird'),
  GoogleMaps = require('googlemaps'),
  gm = Promise.promisifyAll(new GoogleMaps());

return gm.placeSearchAsync(options)
.then(function(response) {
    winston.debug("placeSearch result:", response);
})
.catch(function(e) {
    winston.error("Unable to query google maps api placeSearch:", e);
});
```

Since it's so easy to wrap yourself, I'm not sure if it's worth putting into the library.  @fabriziomoscon ?

**Comment by fabriziomoscon** [comment]
The current `v1` implementation can be used by node 0.8 and 0.10 users as it doesn't require `Promises`. Using a third party `Promises` library inside the this code will add an extra dependency and maintenance costs. In my opinion the simpler the dependencies graph is the better for any library. Unless the use of `Promises` lowers the library maintenance costs or make it possible to achieve more functionalities I would prefer to keep the use of callback.

In the future if the version of node with native `Promises` support will become widespread adopted we could consider a `v2` that drops the support for older node versions and rewrite the code to be `Promises` oriented.

**Comment by vikeen** [comment]
@fabriziomoscon fair enough. Thanks for clarifying.
